// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jogoAnimaisAPI.Data;

#nullable disable

namespace jogoAnimaisAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711194337_alterColumnName")]
    partial class alterColumnName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("jogoAnimaisAPI.Models.Personagens", b =>
                {
                    b.Property<int>("personagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personagemId"));

                    b.Property<string>("personageNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("personagemNome");

                    b.Property<string>("posicaoPersonagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personagemId");

                    b.ToTable("personagens");

                    b.HasData(
                        new
                        {
                            personagemId = 1,
                            personageNome = "zebra",
                            posicaoPersonagem = "Direita"
                        },
                        new
                        {
                            personagemId = 2,
                            personageNome = "leão",
                            posicaoPersonagem = "Direita"
                        },
                        new
                        {
                            personagemId = 3,
                            personageNome = "hipopótamomo",
                            posicaoPersonagem = "Direita"
                        },
                        new
                        {
                            personagemId = 4,
                            personageNome = "guarda",
                            posicaoPersonagem = "Direita"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
