// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jogoAnimaisAPI.Data;

#nullable disable

namespace jogoAnimaisAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711165656_createDb")]
    partial class createDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("jogoAnimaisAPI.Models.Personagens", b =>
                {
                    b.Property<int>("personagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personagemId"));

                    b.Property<string>("personageNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posicaoPersonagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personagemId");

                    b.ToTable("personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
